=== rolud/DistribuitedProgrammingII/lab01/xsd/biblio_e.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://pad.polito.it/dp2/biblio"
	    xmlns:tns="http://pad.polito.it/dp2/biblio" >

	<element name="biblio">
		<complexType>
			<sequence>
				<element name="items">
					<complexType>
						<sequence>
							<element name="book" type="tns:BookType" minOccurs="0" maxOccurs="unbounded" />
							<element name="article" type="tns:ArticleType" minOccurs="0" maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>
				<element name="journals">
					<complexType>
						<sequence>
							<element name="journal" type="tns:JournalType" minOccurs="0" maxOccurs="unbounded">
								<unique name="issueUniqueness">
									<selector xpath="issue" />
									<field xpath="@year" />
									<field xpath="@number" />
								</unique>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
			
		</complexType>
		
		<key name="itemKey">
			<selector xpath="items/*"/>
			<field xpath="@id" />
		</key>
		<keyref name="itemReference" refer="tns:itemKey">
			<selector xpath="items/*/citedBy" />
			<field xpath="." />
		</keyref>
		
		<key name="journalKey">
			<selector xpath="journals/journal"/>
			<field xpath="@issn" />
		</key>
		<keyref name="journalRef" refer="tns:journalKey">
			<selector xpath="items/article" />
			<field xpath="@journal" />
		</keyref>
		
		<key name="issueKey">
			<selector xpath="journals/journal/issue"/>
			<field xpath="@id" />
		</key>
		<keyref name="issueRef" refer="tns:issueKey">
			<selector xpath="items/article" />
			<field xpath="@issue" />
		</keyref>
		
		<unique name="journalUniqueness">
			<selector xpath="journals/journal" />
			<field xpath="@issn"/>
		</unique>
		
		<unique name="bookUniqueness">
			<selector xpath="items/book" />
			<field xpath="@isbn"/>
		</unique>
	</element>
	
	<complexType name="BibliographyItemType">
		<sequence>
			<element name="author" type="string" maxOccurs="unbounded"/>
			<element name="title" type="string" />
			<element name="subtitle" type="string" minOccurs="0"/>
			<element name="citedBy" type="integer" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="integer" use="required" />
	</complexType> 
	
	<complexType name="BookType">
		<complexContent>
			<extension base="tns:BibliographyItemType">	
				<sequence>
					<element name="publisher" type="string" />
				</sequence>
				<attribute name="isbn" type="tns:ISBNCode" use="required" />
				<attribute name="year" type="gYear" use="required" />
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="ArticleType">
		<complexContent>
			<extension base="tns:BibliographyItemType">	
				<attribute name="journal" type="tns:ISSNCode" use="required" />
				<attribute name="issue" type="positiveInteger" use="required" />
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="JournalType">
		<sequence>
			<element name="title" type="string" />
			<element name="publisher" type="string" />
			<element name="issue" type="tns:IssueType" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="issn" type="tns:ISSNCode" use="required" />
	</complexType>
	
	<complexType name="IssueType">
		<attribute name="id" type="positiveInteger" use="required" />
		<attribute name="year" type="gYear" use="required" />
		<attribute name="number" type="positiveInteger" use="required" />
	</complexType>
	
	<simpleType name="ISBNCode">
		<restriction base="string">
		    <pattern value="[0-9]{13}" />
			<pattern value="[0-9]{9}([0-9]|X)" />
		</restriction>
	</simpleType>
	
	<simpleType name="ISSNCode">
		<restriction base="string">
			<pattern value="[0-9]{4}-[0-9]{3}([0-9]|X)"/>
		</restriction>
	</simpleType>
 </schema>

=== rolud/DistribuitedProgrammingII/assignment1c/xsd/biblio_output_2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:biblio xmlns:ns2="http://pad.polito.it/dp2/biblio"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://pad.polito.it/dp2/biblio biblio_e.xsd ">
    <items>
        <book isbn="1548651354" year="2009Z" id="2">
            <author>Frank Turing</author>
            <title>Story of an Automata</title>
            <citedBy>2</citedBy>
            <publisher>Best World Editor</publisher>
        </book>
        <article journal="1120-4000" issue="3" id="0">
            <author>Walter White</author>
            <title>Impact of chemistry on smart drugs</title>
            <citedBy>2</citedBy>
        </article>
        <article journal="1120-4563" issue="14" id="1">
            <author>Albert Heisenberg</author>
            <title>Machine Learning on an ARM processor</title>
            <citedBy>2</citedBy>
        </article>
    </items>
    <journals>
        <journal issn="1120-4563">
            <title>Machine Learning and Articial Intelligence News</title>
            <publisher>RCS MediaGroup</publisher>
            <issue id="4" year="1999Z" number="3"/>
            <issue id="5" year="1999Z" number="8"/>
            <issue id="6" year="1999Z" number="1"/>
            <issue id="7" year="1999Z" number="2"/>
            <issue id="8" year="1999Z" number="7"/>
            <issue id="9" year="1999Z" number="6"/>
            <issue id="10" year="1999Z" number="4"/>
            <issue id="11" year="1999Z" number="5"/>
            <issue id="12" year="1999Z" number="9"/>
            <issue id="13" year="1999Z" number="10"/>
            <issue id="14" year="1999Z" number="11"/>
            <issue id="15" year="1999Z" number="12"/>
        </journal>
        <journal issn="1120-4000">
            <title>Modern Chemistry</title>
            <publisher>Best World Editor</publisher>
            <issue id="0" year="2005Z" number="4"/>
            <issue id="1" year="2005Z" number="3"/>
            <issue id="2" year="2005Z" number="2"/>
            <issue id="3" year="2005Z" number="1"/>
        </journal>
    </journals>
</ns2:biblio>

=== rolud/DistribuitedProgrammingII/assignment1c/temp740401491/xsd/biblio_output_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:biblio xmlns:ns2="http://pad.polito.it/dp2/biblio"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://pad.polito.it/dp2/biblio biblio_e.xsd ">
    <items>
        <book isbn="9788845272" year="1977Z" id="1">
            <author>J.R.R. Tolkien</author>
            <title>The Silmarillion</title>
            <citedBy>0</citedBy>
            <citedBy>2</citedBy>
            <publisher>Bompiani</publisher>
        </book>
        <book isbn="9788845268" year="1937Z" id="0">
            <author>J.R.R. Tolkien</author>
            <title>The Hobbit</title>
            <subtitle>There and Back Again</subtitle>
            <citedBy>2</citedBy>
            <publisher>Bompiani</publisher>
        </book>
        <book isbn="9788848603" year="1954Z" id="2">
            <author>J.R.R. Tolkien</author>
            <title>The Lord Of The Ring</title>
            <subtitle>There and Back Again</subtitle>
            <publisher>Bompiani</publisher>
        </book>
        <article journal="1059-1028" issue="10" id="3">
            <author>Lily Hay Newman</author>
            <title>As 5G Rolls Out, Troubling New Security Flwas Emerge</title>
        </article>
        <article journal="1059-1028" issue="10" id="4">
            <author>Gregory Barber</author>
            <title>The Pursuit of Creativity Can Make Algorithms Much Smarter</title>
        </article>
    </items>
    <journals>
        <journal issn="1059-1028">
            <title>Wired</title>
            <publisher>Cond√© Nast</publisher>
            <issue id="0" year="2019Z" number="4"/>
            <issue id="1" year="2019Z" number="9"/>
            <issue id="2" year="2019Z" number="2"/>
            <issue id="3" year="2019Z" number="1"/>
            <issue id="4" year="2019Z" number="3"/>
            <issue id="5" year="2019Z" number="8"/>
            <issue id="6" year="2019Z" number="7"/>
            <issue id="7" year="2019Z" number="5"/>
            <issue id="8" year="2019Z" number="6"/>
            <issue id="9" year="2019Z" number="10"/>
            <issue id="10" year="2019Z" number="11"/>
            <issue id="11" year="2019Z" number="12"/>
        </journal>
    </journals>
</ns2:biblio>
