=== rolud/DistribuitedProgrammingII/assignment1a/xsd/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="accounts">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="account" type="AccountType" minOccurs="1" maxOccurs="unbounded">
					
					<xsd:unique name="holderUniqueness">
						<xsd:selector xpath="account/holder" />
						<xsd:field xpath="@fiscalID" />
					</xsd:unique>
					<xsd:unique name="yearUniqueness">
						<xsd:selector xpath="yearOperation" />
						<xsd:field xpath="@year" />
					</xsd:unique>
				 </xsd:element>
				
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="accountUniqueness">
			<xsd:selector xpath="account" />
			<xsd:field xpath="@number" />
		</xsd:unique>
		
	</xsd:element>
	
	
	<xsd:complexType name="AccountType">
		<xsd:sequence>
			<xsd:element name="holder" type="HolderType" minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="yearOperation" type="YearOperationType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="number" type="xsd:positiveInteger" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="HolderType">
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="address" type="xsd:string" use="required" />
		<xsd:attribute name="fiscalID" type="FiscalID" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="YearOperationType">
		<xsd:sequence>
			<xsd:element name="operation" type="OperationType" minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="year" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="OperationType">
		<xsd:all>
			<xsd:element name="description" type="xsd:string" minOccurs="0"/>
		</xsd:all>
		<xsd:attribute name="date" type="xsd:date" use="required"/>
		<xsd:attribute name="amount" type="Currency" use="required"/>
	</xsd:complexType>
	
	
	<xsd:simpleType name="Currency">
		<xsd:restriction base="xsd:decimal">
			<xsd:fractionDigits value="2" />
		</xsd:restriction>
	</xsd:simpleType>
	
	
	<!-- FiscalID has 16 alphanumeric characters -->
	<xsd:simpleType name="FiscalID">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z0-9]{16}" />
		</xsd:restriction>
	</xsd:simpleType>
	
 </xsd:schema>

=== rolud/DistribuitedProgrammingII/assignment1a/xsd/accounts.xml
<?xml version="1.0"?>
<accounts xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
    xsd:noNamespaceSchemaLocation="accounts.xsd" >
    <account number="1000">
    	<holder address="Corso Grosseto, 25" name="Gianfranco" fiscalID="AA13AA13AA13AA13"/>    	
    	<holder address="Corso Stati Uniti, 101" name="Alberto" fiscalID="CCC179CCC179CCC1"/>
    	<yearOperation year="2019" >
    		<operation date="2019-10-25" amount="500.00">
    			<description>Pagamento affitto</description>
    		</operation>
    	</yearOperation>
    </account>
    <account number="2000">
    	<holder address="Corso Francia, 312" name="Simone" fiscalID="BBBB1234BBBB1234"/>
    	<holder address="Corso Stati Uniti, 101" name="Alberto" fiscalID="CCC179CCC179CCC1"/>
    	<yearOperation year="2019">
    		<operation date="2019-05-13" amount="219.99"/>
    		<operation date="2019-05-13" amount="69.13">
    			<description>Bolletta</description>
   			</operation>
    	</yearOperation>
    	<yearOperation year="2018">
    		<operation date="2018-05-13" amount="219.99"/>
    		<operation date="2018-05-13" amount="69.13"/>
    		<operation date="2018-01-25" amount="100.00"/>
    	</yearOperation>
    </account>
    <account number="3000">
    	<holder address="Corso Unione Sovietica, 666" name="Valentino" fiscalID="DD66FF99DD66FF99"/>
    	<yearOperation year="1997">
    		<operation date="1997-10-12" amount="300000">
    			<description>Acquisto lavastoviglie</description>
    		</operation>
    	</yearOperation>
    </account>
</accounts>
